[tool.ruff]
line-length = 79
target-version = "py310"

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "S", "U"]

[tool.ruff.lint.per-file-ignores]
"os_client_config/tests/*" = ["S"]
"tools/*" = ["S"]
